// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// ActivityTypeUnspecified is a ActivityType of type Unspecified.
	ActivityTypeUnspecified ActivityType = "Unspecified"
	// ActivityTypeRead is a ActivityType of type Read.
	ActivityTypeRead ActivityType = "Read"
	// ActivityTypeWrite is a ActivityType of type Write.
	ActivityTypeWrite ActivityType = "Write"
	// ActivityTypeSearch is a ActivityType of type Search.
	ActivityTypeSearch ActivityType = "Search"
	// ActivityTypeShell is a ActivityType of type Shell.
	ActivityTypeShell ActivityType = "Shell"
)

var ErrInvalidActivityType = errors.New("not a valid ActivityType")

// String implements the Stringer interface.
func (x ActivityType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ActivityType) IsValid() bool {
	_, err := ParseActivityType(string(x))
	return err == nil
}

var _ActivityTypeValue = map[string]ActivityType{
	"Unspecified": ActivityTypeUnspecified,
	"Read":        ActivityTypeRead,
	"Write":       ActivityTypeWrite,
	"Search":      ActivityTypeSearch,
	"Shell":       ActivityTypeShell,
}

// ParseActivityType attempts to convert a string to a ActivityType.
func ParseActivityType(name string) (ActivityType, error) {
	if x, ok := _ActivityTypeValue[name]; ok {
		return x, nil
	}
	return ActivityType(""), fmt.Errorf("%s is %w", name, ErrInvalidActivityType)
}
