// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// AgentActivityTypeUnspecified is a AgentActivityType of type Unspecified.
	AgentActivityTypeUnspecified AgentActivityType = "Unspecified"
	// AgentActivityTypeStart is a AgentActivityType of type Start.
	AgentActivityTypeStart AgentActivityType = "Start"
	// AgentActivityTypeToolCall is a AgentActivityType of type ToolCall.
	AgentActivityTypeToolCall AgentActivityType = "ToolCall"
	// AgentActivityTypeRead is a AgentActivityType of type Read.
	AgentActivityTypeRead AgentActivityType = "Read"
	// AgentActivityTypeWrite is a AgentActivityType of type Write.
	AgentActivityTypeWrite AgentActivityType = "Write"
	// AgentActivityTypeError is a AgentActivityType of type Error.
	AgentActivityTypeError AgentActivityType = "Error"
	// AgentActivityTypeComplete is a AgentActivityType of type Complete.
	AgentActivityTypeComplete AgentActivityType = "Complete"
)

var ErrInvalidAgentActivityType = errors.New("not a valid AgentActivityType")

// String implements the Stringer interface.
func (x AgentActivityType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AgentActivityType) IsValid() bool {
	_, err := ParseAgentActivityType(string(x))
	return err == nil
}

var _AgentActivityTypeValue = map[string]AgentActivityType{
	"Unspecified": AgentActivityTypeUnspecified,
	"Start":       AgentActivityTypeStart,
	"ToolCall":    AgentActivityTypeToolCall,
	"Read":        AgentActivityTypeRead,
	"Write":       AgentActivityTypeWrite,
	"Error":       AgentActivityTypeError,
	"Complete":    AgentActivityTypeComplete,
}

// ParseAgentActivityType attempts to convert a string to a AgentActivityType.
func ParseAgentActivityType(name string) (AgentActivityType, error) {
	if x, ok := _AgentActivityTypeValue[name]; ok {
		return x, nil
	}
	return AgentActivityType(""), fmt.Errorf("%s is %w", name, ErrInvalidAgentActivityType)
}
