// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// AgentRoleUnspecified is a AgentRole of type Unspecified.
	AgentRoleUnspecified AgentRole = "Unspecified"
	// AgentRolePlanner is a AgentRole of type Planner.
	AgentRolePlanner AgentRole = "Planner"
	// AgentRolePlanReviewer is a AgentRole of type PlanReviewer.
	AgentRolePlanReviewer AgentRole = "PlanReviewer"
	// AgentRoleExecutor is a AgentRole of type Executor.
	AgentRoleExecutor AgentRole = "Executor"
	// AgentRoleReviewer is a AgentRole of type Reviewer.
	AgentRoleReviewer AgentRole = "Reviewer"
)

var ErrInvalidAgentRole = errors.New("not a valid AgentRole")

// String implements the Stringer interface.
func (x AgentRole) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AgentRole) IsValid() bool {
	_, err := ParseAgentRole(string(x))
	return err == nil
}

var _AgentRoleValue = map[string]AgentRole{
	"Unspecified":  AgentRoleUnspecified,
	"Planner":      AgentRolePlanner,
	"PlanReviewer": AgentRolePlanReviewer,
	"Executor":     AgentRoleExecutor,
	"Reviewer":     AgentRoleReviewer,
}

// ParseAgentRole attempts to convert a string to a AgentRole.
func ParseAgentRole(name string) (AgentRole, error) {
	if x, ok := _AgentRoleValue[name]; ok {
		return x, nil
	}
	return AgentRole(""), fmt.Errorf("%s is %w", name, ErrInvalidAgentRole)
}
