// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// FindingSeverityUnspecified is a FindingSeverity of type Unspecified.
	FindingSeverityUnspecified FindingSeverity = "Unspecified"
	// FindingSeverityHigh is a FindingSeverity of type High.
	FindingSeverityHigh FindingSeverity = "High"
	// FindingSeverityMedium is a FindingSeverity of type Medium.
	FindingSeverityMedium FindingSeverity = "Medium"
	// FindingSeverityLow is a FindingSeverity of type Low.
	FindingSeverityLow FindingSeverity = "Low"
)

var ErrInvalidFindingSeverity = errors.New("not a valid FindingSeverity")

// String implements the Stringer interface.
func (x FindingSeverity) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x FindingSeverity) IsValid() bool {
	_, err := ParseFindingSeverity(string(x))
	return err == nil
}

var _FindingSeverityValue = map[string]FindingSeverity{
	"Unspecified": FindingSeverityUnspecified,
	"High":        FindingSeverityHigh,
	"Medium":      FindingSeverityMedium,
	"Low":         FindingSeverityLow,
}

// ParseFindingSeverity attempts to convert a string to a FindingSeverity.
func ParseFindingSeverity(name string) (FindingSeverity, error) {
	if x, ok := _FindingSeverityValue[name]; ok {
		return x, nil
	}
	return FindingSeverity(""), fmt.Errorf("%s is %w", name, ErrInvalidFindingSeverity)
}
