// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// PhaseTypeUnspecified is a PhaseType of type Unspecified.
	PhaseTypeUnspecified PhaseType = "Unspecified"
	// PhaseTypeWorktree is a PhaseType of type Worktree.
	PhaseTypeWorktree PhaseType = "Worktree"
	// PhaseTypePlan is a PhaseType of type Plan.
	PhaseTypePlan PhaseType = "Plan"
	// PhaseTypeExecute is a PhaseType of type Execute.
	PhaseTypeExecute PhaseType = "Execute"
	// PhaseTypeReview is a PhaseType of type Review.
	PhaseTypeReview PhaseType = "Review"
	// PhaseTypeApply is a PhaseType of type Apply.
	PhaseTypeApply PhaseType = "Apply"
)

var ErrInvalidPhaseType = errors.New("not a valid PhaseType")

// String implements the Stringer interface.
func (x PhaseType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x PhaseType) IsValid() bool {
	_, err := ParsePhaseType(string(x))
	return err == nil
}

var _PhaseTypeValue = map[string]PhaseType{
	"Unspecified": PhaseTypeUnspecified,
	"Worktree":    PhaseTypeWorktree,
	"Plan":        PhaseTypePlan,
	"Execute":     PhaseTypeExecute,
	"Review":      PhaseTypeReview,
	"Apply":       PhaseTypeApply,
}

// ParsePhaseType attempts to convert a string to a PhaseType.
func ParsePhaseType(name string) (PhaseType, error) {
	if x, ok := _PhaseTypeValue[name]; ok {
		return x, nil
	}
	return PhaseType(""), fmt.Errorf("%s is %w", name, ErrInvalidPhaseType)
}
