// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// PlanStatusUnspecified is a PlanStatus of type Unspecified.
	PlanStatusUnspecified PlanStatus = "Unspecified"
	// PlanStatusDraft is a PlanStatus of type Draft.
	PlanStatusDraft PlanStatus = "Draft"
	// PlanStatusAccepted is a PlanStatus of type Accepted.
	PlanStatusAccepted PlanStatus = "Accepted"
)

var ErrInvalidPlanStatus = errors.New("not a valid PlanStatus")

// String implements the Stringer interface.
func (x PlanStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x PlanStatus) IsValid() bool {
	_, err := ParsePlanStatus(string(x))
	return err == nil
}

var _PlanStatusValue = map[string]PlanStatus{
	"Unspecified": PlanStatusUnspecified,
	"Draft":       PlanStatusDraft,
	"Accepted":    PlanStatusAccepted,
}

// ParsePlanStatus attempts to convert a string to a PlanStatus.
func ParsePlanStatus(name string) (PlanStatus, error) {
	if x, ok := _PlanStatusValue[name]; ok {
		return x, nil
	}
	return PlanStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidPlanStatus)
}
