// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// ReviewFindingStatusUnspecified is a ReviewFindingStatus of type Unspecified.
	ReviewFindingStatusUnspecified ReviewFindingStatus = "Unspecified"
	// ReviewFindingStatusUnresolved is a ReviewFindingStatus of type Unresolved.
	ReviewFindingStatusUnresolved ReviewFindingStatus = "Unresolved"
	// ReviewFindingStatusIgnored is a ReviewFindingStatus of type Ignored.
	ReviewFindingStatusIgnored ReviewFindingStatus = "Ignored"
	// ReviewFindingStatusRejected is a ReviewFindingStatus of type Rejected.
	ReviewFindingStatusRejected ReviewFindingStatus = "Rejected"
	// ReviewFindingStatusResolved is a ReviewFindingStatus of type Resolved.
	ReviewFindingStatusResolved ReviewFindingStatus = "Resolved"
)

var ErrInvalidReviewFindingStatus = errors.New("not a valid ReviewFindingStatus")

// String implements the Stringer interface.
func (x ReviewFindingStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReviewFindingStatus) IsValid() bool {
	_, err := ParseReviewFindingStatus(string(x))
	return err == nil
}

var _ReviewFindingStatusValue = map[string]ReviewFindingStatus{
	"Unspecified": ReviewFindingStatusUnspecified,
	"Unresolved":  ReviewFindingStatusUnresolved,
	"Ignored":     ReviewFindingStatusIgnored,
	"Rejected":    ReviewFindingStatusRejected,
	"Resolved":    ReviewFindingStatusResolved,
}

// ParseReviewFindingStatus attempts to convert a string to a ReviewFindingStatus.
func ParseReviewFindingStatus(name string) (ReviewFindingStatus, error) {
	if x, ok := _ReviewFindingStatusValue[name]; ok {
		return x, nil
	}
	return ReviewFindingStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidReviewFindingStatus)
}
