// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// StepStatusUnspecified is a StepStatus of type Unspecified.
	StepStatusUnspecified StepStatus = "Unspecified"
	// StepStatusPending is a StepStatus of type Pending.
	StepStatusPending StepStatus = "Pending"
	// StepStatusReady is a StepStatus of type Ready.
	StepStatusReady StepStatus = "Ready"
	// StepStatusRunning is a StepStatus of type Running.
	StepStatusRunning StepStatus = "Running"
	// StepStatusPendingFeedback is a StepStatus of type PendingFeedback.
	StepStatusPendingFeedback StepStatus = "PendingFeedback"
	// StepStatusCompleted is a StepStatus of type Completed.
	StepStatusCompleted StepStatus = "Completed"
	// StepStatusCanceled is a StepStatus of type Canceled.
	StepStatusCanceled StepStatus = "Canceled"
	// StepStatusFailed is a StepStatus of type Failed.
	StepStatusFailed StepStatus = "Failed"
)

var ErrInvalidStepStatus = errors.New("not a valid StepStatus")

// String implements the Stringer interface.
func (x StepStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x StepStatus) IsValid() bool {
	_, err := ParseStepStatus(string(x))
	return err == nil
}

var _StepStatusValue = map[string]StepStatus{
	"Unspecified":     StepStatusUnspecified,
	"Pending":         StepStatusPending,
	"Ready":           StepStatusReady,
	"Running":         StepStatusRunning,
	"PendingFeedback": StepStatusPendingFeedback,
	"Completed":       StepStatusCompleted,
	"Canceled":        StepStatusCanceled,
	"Failed":          StepStatusFailed,
}

// ParseStepStatus attempts to convert a string to a StepStatus.
func ParseStepStatus(name string) (StepStatus, error) {
	if x, ok := _StepStatusValue[name]; ok {
		return x, nil
	}
	return StepStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidStepStatus)
}
