// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// TaskStatusUnspecified is a TaskStatus of type Unspecified.
	TaskStatusUnspecified TaskStatus = "Unspecified"
	// TaskStatusReady is a TaskStatus of type Ready.
	TaskStatusReady TaskStatus = "Ready"
	// TaskStatusRunning is a TaskStatus of type Running.
	TaskStatusRunning TaskStatus = "Running"
	// TaskStatusPendingFeedback is a TaskStatus of type Pending Feedback.
	TaskStatusPendingFeedback TaskStatus = "Pending Feedback"
	// TaskStatusCompleted is a TaskStatus of type Completed.
	TaskStatusCompleted TaskStatus = "Completed"
	// TaskStatusCanceled is a TaskStatus of type Canceled.
	TaskStatusCanceled TaskStatus = "Canceled"
	// TaskStatusFailed is a TaskStatus of type Failed.
	TaskStatusFailed TaskStatus = "Failed"
)

var ErrInvalidTaskStatus = errors.New("not a valid TaskStatus")

// String implements the Stringer interface.
func (x TaskStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TaskStatus) IsValid() bool {
	_, err := ParseTaskStatus(string(x))
	return err == nil
}

var _TaskStatusValue = map[string]TaskStatus{
	"Unspecified":      TaskStatusUnspecified,
	"Ready":            TaskStatusReady,
	"Running":          TaskStatusRunning,
	"Pending Feedback": TaskStatusPendingFeedback,
	"Completed":        TaskStatusCompleted,
	"Canceled":         TaskStatusCanceled,
	"Failed":           TaskStatusFailed,
}

// ParseTaskStatus attempts to convert a string to a TaskStatus.
func ParseTaskStatus(name string) (TaskStatus, error) {
	if x, ok := _TaskStatusValue[name]; ok {
		return x, nil
	}
	return TaskStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidTaskStatus)
}
