// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package harness

import (
	"context"

	"github.com/charlieparkes/harness/internal/harness/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function for the type MockStore
func (_mock *MockStore) CreateTask(ctx context.Context, task model.Task) (model.Task, error) {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 model.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Task) (model.Task, error)); ok {
		return returnFunc(ctx, task)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Task) model.Task); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Get(0).(model.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Task) error); ok {
		r1 = returnFunc(ctx, task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockStore_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task model.Task
func (_e *MockStore_Expecter) CreateTask(ctx any, task any) *MockStore_CreateTask_Call {
	return &MockStore_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, task)}
}

func (_c *MockStore_CreateTask_Call) Run(run func(ctx context.Context, task model.Task)) *MockStore_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Task
		if args[1] != nil {
			arg1 = args[1].(model.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateTask_Call) Return(task1 model.Task, err error) *MockStore_CreateTask_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *MockStore_CreateTask_Call) RunAndReturn(run func(ctx context.Context, task model.Task) (model.Task, error)) *MockStore_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetRunningAgentCount provides a mock function for the type MockStore
func (_mock *MockStore) GetRunningAgentCount(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRunningAgentCount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetRunningAgentCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRunningAgentCount'
type MockStore_GetRunningAgentCount_Call struct {
	*mock.Call
}

// GetRunningAgentCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) GetRunningAgentCount(ctx any) *MockStore_GetRunningAgentCount_Call {
	return &MockStore_GetRunningAgentCount_Call{Call: _e.mock.On("GetRunningAgentCount", ctx)}
}

func (_c *MockStore_GetRunningAgentCount_Call) Run(run func(ctx context.Context)) *MockStore_GetRunningAgentCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_GetRunningAgentCount_Call) Return(n int64, err error) *MockStore_GetRunningAgentCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_GetRunningAgentCount_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockStore_GetRunningAgentCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function for the type MockStore
func (_mock *MockStore) GetTask(ctx context.Context, id string) (model.Task, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 model.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Task, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Task); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockStore_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockStore_Expecter) GetTask(ctx any, id any) *MockStore_GetTask_Call {
	return &MockStore_GetTask_Call{Call: _e.mock.On("GetTask", ctx, id)}
}

func (_c *MockStore_GetTask_Call) Run(run func(ctx context.Context, id string)) *MockStore_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetTask_Call) Return(task model.Task, err error) *MockStore_GetTask_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockStore_GetTask_Call) RunAndReturn(run func(ctx context.Context, id string) (model.Task, error)) *MockStore_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskCount provides a mock function for the type MockStore
func (_mock *MockStore) GetTaskCount(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskCount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetTaskCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskCount'
type MockStore_GetTaskCount_Call struct {
	*mock.Call
}

// GetTaskCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) GetTaskCount(ctx any) *MockStore_GetTaskCount_Call {
	return &MockStore_GetTaskCount_Call{Call: _e.mock.On("GetTaskCount", ctx)}
}

func (_c *MockStore_GetTaskCount_Call) Run(run func(ctx context.Context)) *MockStore_GetTaskCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_GetTaskCount_Call) Return(n int64, err error) *MockStore_GetTaskCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_GetTaskCount_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockStore_GetTaskCount_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function for the type MockStore
func (_mock *MockStore) ListTasks(ctx context.Context) ([]model.Task, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []model.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Task, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Task); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type MockStore_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ListTasks(ctx any) *MockStore_ListTasks_Call {
	return &MockStore_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx)}
}

func (_c *MockStore_ListTasks_Call) Run(run func(ctx context.Context)) *MockStore_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_ListTasks_Call) Return(tasks []model.Task, err error) *MockStore_ListTasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockStore_ListTasks_Call) RunAndReturn(run func(ctx context.Context) ([]model.Task, error)) *MockStore_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}
