// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ui

import (
	"context"

	"github.com/charlieparkes/harness/internal/harness/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStatusStore creates a new instance of MockStatusStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatusStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatusStore {
	mock := &MockStatusStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStatusStore is an autogenerated mock type for the StatusStore type
type MockStatusStore struct {
	mock.Mock
}

type MockStatusStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatusStore) EXPECT() *MockStatusStore_Expecter {
	return &MockStatusStore_Expecter{mock: &_m.Mock}
}

// GetRunningAgentCount provides a mock function for the type MockStatusStore
func (_mock *MockStatusStore) GetRunningAgentCount(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRunningAgentCount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatusStore_GetRunningAgentCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRunningAgentCount'
type MockStatusStore_GetRunningAgentCount_Call struct {
	*mock.Call
}

// GetRunningAgentCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStatusStore_Expecter) GetRunningAgentCount(ctx any) *MockStatusStore_GetRunningAgentCount_Call {
	return &MockStatusStore_GetRunningAgentCount_Call{Call: _e.mock.On("GetRunningAgentCount", ctx)}
}

func (_c *MockStatusStore_GetRunningAgentCount_Call) Run(run func(ctx context.Context)) *MockStatusStore_GetRunningAgentCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatusStore_GetRunningAgentCount_Call) Return(n int64, err error) *MockStatusStore_GetRunningAgentCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStatusStore_GetRunningAgentCount_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockStatusStore_GetRunningAgentCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskCount provides a mock function for the type MockStatusStore
func (_mock *MockStatusStore) GetTaskCount(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskCount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatusStore_GetTaskCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskCount'
type MockStatusStore_GetTaskCount_Call struct {
	*mock.Call
}

// GetTaskCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStatusStore_Expecter) GetTaskCount(ctx any) *MockStatusStore_GetTaskCount_Call {
	return &MockStatusStore_GetTaskCount_Call{Call: _e.mock.On("GetTaskCount", ctx)}
}

func (_c *MockStatusStore_GetTaskCount_Call) Run(run func(ctx context.Context)) *MockStatusStore_GetTaskCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatusStore_GetTaskCount_Call) Return(n int64, err error) *MockStatusStore_GetTaskCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStatusStore_GetTaskCount_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockStatusStore_GetTaskCount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTasksStore creates a new instance of MockTasksStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTasksStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTasksStore {
	mock := &MockTasksStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTasksStore is an autogenerated mock type for the TasksStore type
type MockTasksStore struct {
	mock.Mock
}

type MockTasksStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTasksStore) EXPECT() *MockTasksStore_Expecter {
	return &MockTasksStore_Expecter{mock: &_m.Mock}
}

// ListTasks provides a mock function for the type MockTasksStore
func (_mock *MockTasksStore) ListTasks(ctx context.Context) ([]model.Task, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []model.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Task, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Task); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTasksStore_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type MockTasksStore_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTasksStore_Expecter) ListTasks(ctx any) *MockTasksStore_ListTasks_Call {
	return &MockTasksStore_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx)}
}

func (_c *MockTasksStore_ListTasks_Call) Run(run func(ctx context.Context)) *MockTasksStore_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTasksStore_ListTasks_Call) Return(tasks []model.Task, err error) *MockTasksStore_ListTasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTasksStore_ListTasks_Call) RunAndReturn(run func(ctx context.Context) ([]model.Task, error)) *MockTasksStore_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// GetRunningAgentCount provides a mock function for the type MockStore
func (_mock *MockStore) GetRunningAgentCount(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRunningAgentCount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetRunningAgentCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRunningAgentCount'
type MockStore_GetRunningAgentCount_Call struct {
	*mock.Call
}

// GetRunningAgentCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) GetRunningAgentCount(ctx any) *MockStore_GetRunningAgentCount_Call {
	return &MockStore_GetRunningAgentCount_Call{Call: _e.mock.On("GetRunningAgentCount", ctx)}
}

func (_c *MockStore_GetRunningAgentCount_Call) Run(run func(ctx context.Context)) *MockStore_GetRunningAgentCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_GetRunningAgentCount_Call) Return(n int64, err error) *MockStore_GetRunningAgentCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_GetRunningAgentCount_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockStore_GetRunningAgentCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskCount provides a mock function for the type MockStore
func (_mock *MockStore) GetTaskCount(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskCount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetTaskCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskCount'
type MockStore_GetTaskCount_Call struct {
	*mock.Call
}

// GetTaskCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) GetTaskCount(ctx any) *MockStore_GetTaskCount_Call {
	return &MockStore_GetTaskCount_Call{Call: _e.mock.On("GetTaskCount", ctx)}
}

func (_c *MockStore_GetTaskCount_Call) Run(run func(ctx context.Context)) *MockStore_GetTaskCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_GetTaskCount_Call) Return(n int64, err error) *MockStore_GetTaskCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_GetTaskCount_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockStore_GetTaskCount_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function for the type MockStore
func (_mock *MockStore) ListTasks(ctx context.Context) ([]model.Task, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []model.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Task, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Task); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type MockStore_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ListTasks(ctx any) *MockStore_ListTasks_Call {
	return &MockStore_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx)}
}

func (_c *MockStore_ListTasks_Call) Run(run func(ctx context.Context)) *MockStore_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_ListTasks_Call) Return(tasks []model.Task, err error) *MockStore_ListTasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockStore_ListTasks_Call) RunAndReturn(run func(ctx context.Context) ([]model.Task, error)) *MockStore_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUIView creates a new instance of MockUIView. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUIView(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUIView {
	mock := &MockUIView{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUIView is an autogenerated mock type for the UIView type
type MockUIView struct {
	mock.Mock
}

type MockUIView_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUIView) EXPECT() *MockUIView_Expecter {
	return &MockUIView_Expecter{mock: &_m.Mock}
}

// Name provides a mock function for the type MockUIView
func (_mock *MockUIView) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockUIView_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockUIView_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockUIView_Expecter) Name() *MockUIView_Name_Call {
	return &MockUIView_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockUIView_Name_Call) Run(run func()) *MockUIView_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUIView_Name_Call) Return(s string) *MockUIView_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockUIView_Name_Call) RunAndReturn(run func() string) *MockUIView_Name_Call {
	_c.Call.Return(run)
	return _c
}

// View provides a mock function for the type MockUIView
func (_mock *MockUIView) View() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for View")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockUIView_View_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'View'
type MockUIView_View_Call struct {
	*mock.Call
}

// View is a helper method to define mock.On call
func (_e *MockUIView_Expecter) View() *MockUIView_View_Call {
	return &MockUIView_View_Call{Call: _e.mock.On("View")}
}

func (_c *MockUIView_View_Call) Run(run func()) *MockUIView_View_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUIView_View_Call) Return(s string) *MockUIView_View_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockUIView_View_Call) RunAndReturn(run func() string) *MockUIView_View_Call {
	_c.Call.Return(run)
	return _c
}
