// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package ui

import (
	"errors"
	"fmt"
)

const (
	// ViewTypeTasks is a ViewType of type Tasks.
	ViewTypeTasks ViewType = iota
	// ViewTypeExample is a ViewType of type Example.
	ViewTypeExample
)

var ErrInvalidViewType = errors.New("not a valid ViewType")

const _ViewTypeName = "tasksexample"

var _ViewTypeMap = map[ViewType]string{
	ViewTypeTasks:   _ViewTypeName[0:5],
	ViewTypeExample: _ViewTypeName[5:12],
}

// String implements the Stringer interface.
func (x ViewType) String() string {
	if str, ok := _ViewTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ViewType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ViewType) IsValid() bool {
	_, ok := _ViewTypeMap[x]
	return ok
}

var _ViewTypeValue = map[string]ViewType{
	_ViewTypeName[0:5]:  ViewTypeTasks,
	_ViewTypeName[5:12]: ViewTypeExample,
}

// ParseViewType attempts to convert a string to a ViewType.
func ParseViewType(name string) (ViewType, error) {
	if x, ok := _ViewTypeValue[name]; ok {
		return x, nil
	}
	return ViewType(0), fmt.Errorf("%s is %w", name, ErrInvalidViewType)
}
