// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// AutomationPolicyTypeUnspecified is a AutomationPolicyType of type Unspecified.
	AutomationPolicyTypeUnspecified AutomationPolicyType = "Unspecified"
	// AutomationPolicyTypeManual is a AutomationPolicyType of type Manual.
	AutomationPolicyTypeManual AutomationPolicyType = "Manual"
	// AutomationPolicyTypeAutomatic is a AutomationPolicyType of type Automatic.
	AutomationPolicyTypeAutomatic AutomationPolicyType = "Automatic"
)

var ErrInvalidAutomationPolicyType = errors.New("not a valid AutomationPolicyType")

// String implements the Stringer interface.
func (x AutomationPolicyType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AutomationPolicyType) IsValid() bool {
	_, err := ParseAutomationPolicyType(string(x))
	return err == nil
}

var _AutomationPolicyTypeValue = map[string]AutomationPolicyType{
	"Unspecified": AutomationPolicyTypeUnspecified,
	"Manual":      AutomationPolicyTypeManual,
	"Automatic":   AutomationPolicyTypeAutomatic,
}

// ParseAutomationPolicyType attempts to convert a string to a AutomationPolicyType.
func ParseAutomationPolicyType(name string) (AutomationPolicyType, error) {
	if x, ok := _AutomationPolicyTypeValue[name]; ok {
		return x, nil
	}
	return AutomationPolicyType(""), fmt.Errorf("%s is %w", name, ErrInvalidAutomationPolicyType)
}
