// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// ReviewFindingSeverityUnspecified is a ReviewFindingSeverity of type Unspecified.
	ReviewFindingSeverityUnspecified ReviewFindingSeverity = "Unspecified"
	// ReviewFindingSeverityLow is a ReviewFindingSeverity of type Low.
	ReviewFindingSeverityLow ReviewFindingSeverity = "Low"
	// ReviewFindingSeverityMedium is a ReviewFindingSeverity of type Medium.
	ReviewFindingSeverityMedium ReviewFindingSeverity = "Medium"
	// ReviewFindingSeverityHigh is a ReviewFindingSeverity of type High.
	ReviewFindingSeverityHigh ReviewFindingSeverity = "High"
)

var ErrInvalidReviewFindingSeverity = errors.New("not a valid ReviewFindingSeverity")

// String implements the Stringer interface.
func (x ReviewFindingSeverity) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReviewFindingSeverity) IsValid() bool {
	_, err := ParseReviewFindingSeverity(string(x))
	return err == nil
}

var _ReviewFindingSeverityValue = map[string]ReviewFindingSeverity{
	"Unspecified": ReviewFindingSeverityUnspecified,
	"Low":         ReviewFindingSeverityLow,
	"Medium":      ReviewFindingSeverityMedium,
	"High":        ReviewFindingSeverityHigh,
}

// ParseReviewFindingSeverity attempts to convert a string to a ReviewFindingSeverity.
func ParseReviewFindingSeverity(name string) (ReviewFindingSeverity, error) {
	if x, ok := _ReviewFindingSeverityValue[name]; ok {
		return x, nil
	}
	return ReviewFindingSeverity(""), fmt.Errorf("%s is %w", name, ErrInvalidReviewFindingSeverity)
}
