// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// PhaseStatusUnspecified is a PhaseStatus of type Unspecified.
	PhaseStatusUnspecified PhaseStatus = "Unspecified"
	// PhaseStatusPending is a PhaseStatus of type Pending.
	PhaseStatusPending PhaseStatus = "Pending"
	// PhaseStatusReady is a PhaseStatus of type Ready.
	PhaseStatusReady PhaseStatus = "Ready"
	// PhaseStatusRunning is a PhaseStatus of type Running.
	PhaseStatusRunning PhaseStatus = "Running"
	// PhaseStatusFeedback is a PhaseStatus of type Feedback.
	PhaseStatusFeedback PhaseStatus = "Feedback"
	// PhaseStatusCompleted is a PhaseStatus of type Completed.
	PhaseStatusCompleted PhaseStatus = "Completed"
	// PhaseStatusCanceled is a PhaseStatus of type Canceled.
	PhaseStatusCanceled PhaseStatus = "Canceled"
	// PhaseStatusFailed is a PhaseStatus of type Failed.
	PhaseStatusFailed PhaseStatus = "Failed"
)

var ErrInvalidPhaseStatus = errors.New("not a valid PhaseStatus")

// String implements the Stringer interface.
func (x PhaseStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x PhaseStatus) IsValid() bool {
	_, err := ParsePhaseStatus(string(x))
	return err == nil
}

var _PhaseStatusValue = map[string]PhaseStatus{
	"Unspecified": PhaseStatusUnspecified,
	"Pending":     PhaseStatusPending,
	"Ready":       PhaseStatusReady,
	"Running":     PhaseStatusRunning,
	"Feedback":    PhaseStatusFeedback,
	"Completed":   PhaseStatusCompleted,
	"Canceled":    PhaseStatusCanceled,
	"Failed":      PhaseStatusFailed,
}

// ParsePhaseStatus attempts to convert a string to a PhaseStatus.
func ParsePhaseStatus(name string) (PhaseStatus, error) {
	if x, ok := _PhaseStatusValue[name]; ok {
		return x, nil
	}
	return PhaseStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidPhaseStatus)
}
