// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// ReviewDecisionUnspecified is a ReviewDecision of type Unspecified.
	ReviewDecisionUnspecified ReviewDecision = "Unspecified"
	// ReviewDecisionChangesRequested is a ReviewDecision of type ChangesRequested.
	ReviewDecisionChangesRequested ReviewDecision = "ChangesRequested"
	// ReviewDecisionApproved is a ReviewDecision of type Approved.
	ReviewDecisionApproved ReviewDecision = "Approved"
	// ReviewDecisionRejected is a ReviewDecision of type Rejected.
	ReviewDecisionRejected ReviewDecision = "Rejected"
)

var ErrInvalidReviewDecision = errors.New("not a valid ReviewDecision")

// String implements the Stringer interface.
func (x ReviewDecision) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReviewDecision) IsValid() bool {
	_, err := ParseReviewDecision(string(x))
	return err == nil
}

var _ReviewDecisionValue = map[string]ReviewDecision{
	"Unspecified":      ReviewDecisionUnspecified,
	"ChangesRequested": ReviewDecisionChangesRequested,
	"Approved":         ReviewDecisionApproved,
	"Rejected":         ReviewDecisionRejected,
}

// ParseReviewDecision attempts to convert a string to a ReviewDecision.
func ParseReviewDecision(name string) (ReviewDecision, error) {
	if x, ok := _ReviewDecisionValue[name]; ok {
		return x, nil
	}
	return ReviewDecision(""), fmt.Errorf("%s is %w", name, ErrInvalidReviewDecision)
}
