// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// ReviewFindingCategoryUnspecified is a ReviewFindingCategory of type Unspecified.
	ReviewFindingCategoryUnspecified ReviewFindingCategory = "Unspecified"
	// ReviewFindingCategoryBug is a ReviewFindingCategory of type Bug.
	ReviewFindingCategoryBug ReviewFindingCategory = "Bug"
)

var ErrInvalidReviewFindingCategory = errors.New("not a valid ReviewFindingCategory")

// String implements the Stringer interface.
func (x ReviewFindingCategory) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReviewFindingCategory) IsValid() bool {
	_, err := ParseReviewFindingCategory(string(x))
	return err == nil
}

var _ReviewFindingCategoryValue = map[string]ReviewFindingCategory{
	"Unspecified": ReviewFindingCategoryUnspecified,
	"Bug":         ReviewFindingCategoryBug,
}

// ParseReviewFindingCategory attempts to convert a string to a ReviewFindingCategory.
func ParseReviewFindingCategory(name string) (ReviewFindingCategory, error) {
	if x, ok := _ReviewFindingCategoryValue[name]; ok {
		return x, nil
	}
	return ReviewFindingCategory(""), fmt.Errorf("%s is %w", name, ErrInvalidReviewFindingCategory)
}
