// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// TargetPurposeUnspecified is a TargetPurpose of type Unspecified.
	TargetPurposeUnspecified TargetPurpose = "Unspecified"
	// TargetPurposeRead is a TargetPurpose of type Read.
	TargetPurposeRead TargetPurpose = "Read"
	// TargetPurposeReadWrite is a TargetPurpose of type ReadWrite.
	TargetPurposeReadWrite TargetPurpose = "ReadWrite"
)

var ErrInvalidTargetPurpose = errors.New("not a valid TargetPurpose")

// String implements the Stringer interface.
func (x TargetPurpose) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TargetPurpose) IsValid() bool {
	_, err := ParseTargetPurpose(string(x))
	return err == nil
}

var _TargetPurposeValue = map[string]TargetPurpose{
	"Unspecified": TargetPurposeUnspecified,
	"Read":        TargetPurposeRead,
	"ReadWrite":   TargetPurposeReadWrite,
}

// ParseTargetPurpose attempts to convert a string to a TargetPurpose.
func ParseTargetPurpose(name string) (TargetPurpose, error) {
	if x, ok := _TargetPurposeValue[name]; ok {
		return x, nil
	}
	return TargetPurpose(""), fmt.Errorf("%s is %w", name, ErrInvalidTargetPurpose)
}
