// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// TargetTypeUnspecified is a TargetType of type Unspecified.
	TargetTypeUnspecified TargetType = "Unspecified"
	// TargetTypeGeneric is a TargetType of type Generic.
	TargetTypeGeneric TargetType = "Generic"
	// TargetTypeVersionControlGit is a TargetType of type VersionControlGit.
	TargetTypeVersionControlGit TargetType = "VersionControlGit"
)

var ErrInvalidTargetType = errors.New("not a valid TargetType")

// String implements the Stringer interface.
func (x TargetType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TargetType) IsValid() bool {
	_, err := ParseTargetType(string(x))
	return err == nil
}

var _TargetTypeValue = map[string]TargetType{
	"Unspecified":       TargetTypeUnspecified,
	"Generic":           TargetTypeGeneric,
	"VersionControlGit": TargetTypeVersionControlGit,
}

// ParseTargetType attempts to convert a string to a TargetType.
func ParseTargetType(name string) (TargetType, error) {
	if x, ok := _TargetTypeValue[name]; ok {
		return x, nil
	}
	return TargetType(""), fmt.Errorf("%s is %w", name, ErrInvalidTargetType)
}
