// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// WorktreeStatusUnspecified is a WorktreeStatus of type Unspecified.
	WorktreeStatusUnspecified WorktreeStatus = "Unspecified"
	// WorktreeStatusPending is a WorktreeStatus of type Pending.
	WorktreeStatusPending WorktreeStatus = "Pending"
	// WorktreeStatusPreparing is a WorktreeStatus of type Preparing.
	WorktreeStatusPreparing WorktreeStatus = "Preparing"
	// WorktreeStatusReady is a WorktreeStatus of type Ready.
	WorktreeStatusReady WorktreeStatus = "Ready"
	// WorktreeStatusRemoved is a WorktreeStatus of type Removed.
	WorktreeStatusRemoved WorktreeStatus = "Removed"
)

var ErrInvalidWorktreeStatus = errors.New("not a valid WorktreeStatus")

// String implements the Stringer interface.
func (x WorktreeStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x WorktreeStatus) IsValid() bool {
	_, err := ParseWorktreeStatus(string(x))
	return err == nil
}

var _WorktreeStatusValue = map[string]WorktreeStatus{
	"Unspecified": WorktreeStatusUnspecified,
	"Pending":     WorktreeStatusPending,
	"Preparing":   WorktreeStatusPreparing,
	"Ready":       WorktreeStatusReady,
	"Removed":     WorktreeStatusRemoved,
}

// ParseWorktreeStatus attempts to convert a string to a WorktreeStatus.
func ParseWorktreeStatus(name string) (WorktreeStatus, error) {
	if x, ok := _WorktreeStatusValue[name]; ok {
		return x, nil
	}
	return WorktreeStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidWorktreeStatus)
}
