// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package styles

import (
	"errors"
	"fmt"
)

const (
	// ColorTypeBg is a ColorType of type bg.
	ColorTypeBg ColorType = "bg"
	// ColorTypeFg is a ColorType of type fg.
	ColorTypeFg ColorType = "fg"
	// ColorTypeFgMuted is a ColorType of type fg-muted.
	ColorTypeFgMuted ColorType = "fg-muted"
	// ColorTypeAccent is a ColorType of type accent.
	ColorTypeAccent ColorType = "accent"
	// ColorTypeBorder is a ColorType of type border.
	ColorTypeBorder ColorType = "border"
	// ColorTypeSuccess is a ColorType of type success.
	ColorTypeSuccess ColorType = "success"
	// ColorTypeSuccessMuted is a ColorType of type success-muted.
	ColorTypeSuccessMuted ColorType = "success-muted"
	// ColorTypeWarning is a ColorType of type warning.
	ColorTypeWarning ColorType = "warning"
	// ColorTypeWarningMuted is a ColorType of type warning-muted.
	ColorTypeWarningMuted ColorType = "warning-muted"
	// ColorTypeDanger is a ColorType of type danger.
	ColorTypeDanger ColorType = "danger"
	// ColorTypeDangerMuted is a ColorType of type danger-muted.
	ColorTypeDangerMuted ColorType = "danger-muted"
)

var ErrInvalidColorType = errors.New("not a valid ColorType")

// String implements the Stringer interface.
func (x ColorType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ColorType) IsValid() bool {
	_, err := ParseColorType(string(x))
	return err == nil
}

var _ColorTypeValue = map[string]ColorType{
	"bg":            ColorTypeBg,
	"fg":            ColorTypeFg,
	"fg-muted":      ColorTypeFgMuted,
	"accent":        ColorTypeAccent,
	"border":        ColorTypeBorder,
	"success":       ColorTypeSuccess,
	"success-muted": ColorTypeSuccessMuted,
	"warning":       ColorTypeWarning,
	"warning-muted": ColorTypeWarningMuted,
	"danger":        ColorTypeDanger,
	"danger-muted":  ColorTypeDangerMuted,
}

// ParseColorType attempts to convert a string to a ColorType.
func ParseColorType(name string) (ColorType, error) {
	if x, ok := _ColorTypeValue[name]; ok {
		return x, nil
	}
	return ColorType(""), fmt.Errorf("%s is %w", name, ErrInvalidColorType)
}
